{% set name = "felyxcontrib-metrics-workflow" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/felyx/felyxcontribs_metrics_workflow/-/archive/{{ version }}/felyxcontribs_metrics_workflow-{{ version }}.tar.gz
  sha256: c6ddf3fec47b0794cffc65447fec5ca2a96cb175e7dcb6b0c5caf59c3f09d9c4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5.0
    - pyresample >=1.16.0,<1.17

    
test:
  requires:
    - python {{ python_min }}
  imports:
    - felyxcontribs_metrics_workflow


about:
  home: https://gitlab.ifremer.fr/felyx/felyxcontribs_metrics_workflow
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: felyx extensions for workflow metrics.

extra:
  recipe-maintainers:
    - marie59
